#[Info]
site_name: Xiaoming's library
site_url: #网站地址
site_author: xiaoming
#[UI]
theme:
  name: material
  language: zh # 一些提示性的文字会变成中文
  font: # 字体
    text: Roboto
    code: Roboto Mono
  # logo: assets/logo.png #logo
  # 颜色设置，包含模式切换
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: cyan # header颜色
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: indigo 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式


  features:
    - navigation.toc  # 显示目录
    - navigation.toc.sticky  # 目录固定在侧边
    # - header.autohide  #自动隐藏 
    # - navigation.instant #即时加载
    # - navigation.instant.prefetch # 悬停在页面上时便开始即使加载
    # - navigation.instant.progress #加载进度条
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    # - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.path # 当前文章路径
    # - navigation.expand # 打开Tab时左侧目录全部展开
    # - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    # - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    


#   icon: 
#     repo: fontawesome/brands/github #右上角图标
# edit_uri: edit/main/docs # 编辑按钮跳转的链接 
# repo_url: https://github.com/Wcowin/mymkdocs # 右上角点击跳转的链接
# repo_name: Wcowin.github.io # 右上角的名字

# [Navigtion]
# 导航树，记得后面文件需要加路径
nav:
  - 'Csbase':
    - 'System Design Question':
      - 'Design Coffee Machine': 'CSbase/system design question/Design Coffee Machine.md'
      - 'Object Oriented Design Interview': 'CSbase/system design question/Object-Oriented Design Interview.md'
    - '数据结构与算法':
      - '未命名': 'CSbase/数据结构与算法/未命名.md'
    - '计算机网络':
      - '在Ubuntu上打开端口': 'CSbase/计算机网络/在Ubuntu上打开端口.md'
      - '网络拥塞管理和避免（队列调度算法Fifo，Sp，Rr，Wrr，Drr，Mdrr，Wdrr，Wfq）': 'CSbase/计算机网络/网络拥塞管理和避免（队列调度算法FIFO，SP，RR，WRR，DRR，MDRR，WDRR，WFQ）.md'
      - '计算机网络Base': 'CSbase/计算机网络/计算机网络base.md'
    - '软件工程':
      - 'Uml建模': 'CSbase/软件工程/UML建模.md'
    - 'Cpu Gpu原理': 'CSbase/CPU GPU原理.md'
    - 'Git': 'CSbase/git.md'
    - 'Json Schema': 'CSbase/json schema.md'
    - 'Vim': 'CSbase/Vim.md'
    - '位运算': 'CSbase/位运算.md'
    - '哈希表 Hash Table': 'CSbase/哈希表 hash table.md'
    - '多线程和多线程同步': 'CSbase/多线程和多线程同步.md'
    - '大小端问题': 'CSbase/大小端问题.md'
    - '序列化': 'CSbase/序列化.md'
    - '线程与进程': 'CSbase/线程与进程.md'
  - 'Leetcode':
    - 'Leetcode':
      - '两数之和': 'leetcode/leetcode/1.两数之和.md'
      - '两数相加': 'leetcode/leetcode/2.两数相加.md'
      - '寻找两个正序数组的中位数': 'leetcode/leetcode/4.寻找两个正序数组的中位数.md'
      - '盛水最多的容器': 'leetcode/leetcode/11.盛水最多的容器.md'
      - '三数之和': 'leetcode/leetcode/15. 三数之和.md'
      - '有效的括号': 'leetcode/leetcode/20. 有效的括号.md'
      - '移除元素': 'leetcode/leetcode/27.移除元素.md'
      - '搜索旋转排序数组': 'leetcode/leetcode/33. 搜索旋转排序数组.md'
      - '在排序数组中查找元素的第一个和最后一个位置': 'leetcode/leetcode/34.在排序数组中查找元素的第一个和最后一个位置.md'
      - '搜索插入位置': 'leetcode/leetcode/35.搜索插入位置.md'
      - '接雨水': 'leetcode/leetcode/42. 接雨水.md'
      - '字母异位词分组': 'leetcode/leetcode/49. 字母异位词分组.md'
      - '螺旋矩阵Ⅱ': 'leetcode/leetcode/59. 螺旋矩阵Ⅱ.md'
      - 'X的平方根': 'leetcode/leetcode/69. x的平方根.md'
      - '搜索二维矩阵': 'leetcode/leetcode/74. 搜索二维矩阵.md'
      - '二叉树的最大深度': 'leetcode/leetcode/104. 二叉树的最大深度.md'
      - '最长连续序列': 'leetcode/leetcode/128. 最长连续序列.md'
      - '逆波兰表达式求值': 'leetcode/leetcode/150. 逆波兰表达式求值.md'
      - '寻找旋转排序数组中的最小值': 'leetcode/leetcode/153.寻找旋转排序数组中的最小值.md'
      - '两数之和 Ii   输入有序数组': 'leetcode/leetcode/167. 两数之和 II - 输入有序数组.md'
      - '打家劫舍': 'leetcode/leetcode/198.打家劫舍.md'
      - '移除链表元素': 'leetcode/leetcode/203.移除链表元素.md'
      - '反转链表': 'leetcode/leetcode/206.反转链表.md'
      - '长度最小的子数组': 'leetcode/leetcode/209. 长度最小的子数组.md'
      - '用队列实现栈': 'leetcode/leetcode/225. 用队列实现栈.md'
      - '用栈实现队列': 'leetcode/leetcode/232.用栈实现队列.md'
      - '滑动窗口最大值': 'leetcode/leetcode/239.滑动窗口最大值.md'
      - '移动零': 'leetcode/leetcode/283. 移动零.md'
      - '前 K 个高频元素': 'leetcode/leetcode/347.前 K 个高频元素.md'
      - '用 Rand7() 实现 Rand10()': 'leetcode/leetcode/470. 用 Rand7() 实现 Rand10().md'
      - '在圆内随机生成点': 'leetcode/leetcode/478. 在圆内随机生成点.md'
      - '反转字符串 Ii': 'leetcode/leetcode/541. 反转字符串 II.md'
      - '和为 K 的子数组': 'leetcode/leetcode/560. 和为 K 的子数组.md'
      - '设计链表': 'leetcode/leetcode/707. 设计链表.md'
      - '寻找数组的中心下标': 'leetcode/leetcode/724. 寻找数组的中心下标.md'
      - '有序数组的平方': 'leetcode/leetcode/977.有序数组的平方.md'
      - '总持续时间可被 60 整除的歌曲': 'leetcode/leetcode/1010. 总持续时间可被 60 整除的歌曲.md'
      - '删除字符串中的所有相邻重复项': 'leetcode/leetcode/1047. 删除字符串中的所有相邻重复项.md'
      - '数青蛙': 'leetcode/leetcode/1419. 数青蛙.md'
      - '到家的最少跳跃次数': 'leetcode/leetcode/1654. 到家的最少跳跃次数.md'
      - '找出所有子集的异或总和再求和': 'leetcode/leetcode/1863. 找出所有子集的异或总和再求和.md'
    - '二分查找': 'leetcode/二分查找.md'
    - '华为9.27笔试': 'leetcode/华为9.27笔试.md'
    - '20240911华为笔试': 'leetcode/20240911华为笔试.md'
    - '并查集': 'leetcode/并查集.md'
    - '排序算法': 'leetcode/排序算法.md'
  - '关系抽取':
    - '': '关系抽取/index.md'
    - 'Re Matching： A Fine Grained Semantic Matching Method For Zero Shot Relation Extraction': '关系抽取/RE-Matching： A Fine-Grained Semantic Matching Method for Zero-Shot Relation Extraction.md'
    - 'Revisiting Relation Extraction In The Era Of Large Language Models': '关系抽取/Revisiting Relation Extraction in the era of Large Language Models.md'
  - '基础知识':
    - 'Evaluation Metrics': '基础知识/evaluation metrics.md'
  - '杂项':
    - "let's Encrypt 免费证书": "杂项/let's Encrypt 免费ssl证书.md"
    - "ddns-go 动态域名解析": "杂项/ddns-go 动态域名解析.md"
  - '': 'index.md'





copyright: Copyright &copy; 2025 xiaoming. All rights reserved. # 左下角的版权声明


extra:
  # generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  feedback:

  social: #联系方式之类的 
  #   - icon: fontawesome/brands/twitter 
  #     link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/DylanMing/library
  #   - icon: fontawesome/brands/bilibili
  #     link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
  #   - icon: fontawesome/solid/paper-plane
  #     link: mailto:<1135801806@qq.com> #联系方式
#   多语言文档设置
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Deutsch
#       link: /de/
#       lang: de


#cookie 
  # analytics: 
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/heart
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/heart-broken
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好~
    #描述

plugins:
  - search
  - tags  #标签
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      baselevel: 2 # 原有的目录是从h2开始，这里设置为2，那么所有H1都会渲染为h2
      # toc_depth: 3 # 目录显示的最大层级（默认1-6）
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - footnotes #脚注
  - tables #表格


extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
